[Interface]
PrivateKey = 8IzOwlTzPuAqvLtWKvmGw32pNPSwZeJKwMqRhhtAUmo=
Address = 10.66.66.2/32,fd42:42:42::2/128
DNS = 1.1.1.1,1.0.0.1

# Uncomment the next line to set a custom MTU
# This might impact performance, so use it only if you know what you are doing
# See https://github.com/nitred/nr-wg-mtu-finder to find your optimal MTU
# MTU = 1420

[Peer]
PublicKey = uhGnhYMGGPHVuVu0j94eixnGeU0G9dm5SOyz+UKnXSE=
PresharedKey = as1mKqcnkUOzfCaN+zERtKKPspegsrVHPTv6r6YQu6k=
Endpoint = 144.31.201.14:51820
AllowedIPs = 0.0.0.0/0,::/0
